- .github/workflows/ci.yml
This change makes sure to use proper main branch in the CI workflow
trigger filters.
> Fix running GHA on pushes and PRs

- README.md
- tox.ini
We've made a change renaming this image once today but it seems there's a desire to do it again. To avoid miscommunication, I've written down some action items to make this happen. They should be done in the order they are listed.
Action item for  @ssbarnea:
Everyone else:
> Rename the container image to `ansible/creator-ee`

- requirements.txt
- tox.ini
As ansible-builder become stable we do not want to use unreleased
versions.
This change also prepares for refactoring dependency building and
future adoption of pip-tools/requirements.txt/constraints.txt, like
we already had on toolset project.
> Ensure we use only released ansible-builder

- tox.ini
Fixes problems with docker and podman caused by lack of passing essential variables used by them, especially when container engines are remote.
> chore: add container vars to passenv

- .github/workflows/ci.yml
- tox.ini
Fix bug where running podman would have also involved
building container with docker first, doubling the runtime.
`check-diff` should not have imported commands from
root tox env as it would mean that chaining tox envs would
trigger multiple executions.
Also running check-diff on lint and deps was not desired.
> chore: fix use of check-diff

- _build/requirements.txt
- _build/requirements.yml
As this image is superseding the ansible toolset image, it should aim at feature parity with its precursor.
This change adds the molecule podman driver, and its necessary dependencies. This also includes the `containers.podman` ansible collection, as written in the molecule-podman README.
Partly fixes: ansible#20
> Add molecule-podman driver

- _build/requirements.txt
- _build/requirements.yml
As this image is superseding the ansible toolset image, it should aim at feature parity with its precursor.
This change adds the molecule docker driver, and its necessary dependencies. This also includes the `community.docker` ansible collection, as written in the [molecule-docker README](https://github.com/ansible-community/molecule-docker/blob/main/README.rst).
Partly fixes: #20
> Add docker molecule driver

- _build/requirements.txt
As this image is superseding the ansible toolset image, it should aim at feature parity with its precursor.
This change adds the molecule containers driver - which is a drop-in replacement for the existing Docker and Podman drivers - and its necessary dependencies. This also includes the community.docker and `containers.podman` ansible collections, as written in the `molecule-docker` and `molecule-podman` README.
This partly fixes: ansible#20
This should be merged only if #22 and #23 are successfully merged.
> Add molecule-containers driver

- _build/requirements.txt
As this image is superseding the ansible toolset image, it should aim at feature parity with its precursor.
This change adds the molecule openstack driver, and its necessary dependencies.
See: https://github.com/ansible/creator-ee/issues/20
> Add molecule-openstack driver

- .github/workflows/release.yml
As yesterday release attempt failed to trigger the pipeline we
correct the trigger event. Based on configuration known to be working
from other devtools projects like ansible-lint and molecule.
> Fix release pipeline to trigger on published event

- Containerfile
- _build/bindep.txt
- execution-environment.yml
In #22 and #23 the podman and docker molecule drivers were added, but the respective binaries are still missing.
This commit adds the necessary dependencies to the execution enviroments bindep.txt.
This commit also adds some CLI commands to check we do not remove them inadvertently and output some helpful version information at build time.
> Add podman and docker binaries

- _build/requirements.in
- tox.ini
We also had to increase the size check because changes in rpms increase the image size above our self imposed limit.
> Add requirements.in file for dependabot

- _build/requirements.in
- _build/requirements.txt
This change is needed because community.docker collections has
a requirements on python package docker-compose<2.0 and that is
causing other conflicts with our dependencies. As new docker-compose
versions are no longer on pypi, the only workaround would for the
collection to make that dependency soft.
This will not be added back unless that conflicts are addressed.
That was blocking ansible-lint version upgrade inside the container, as seen on https://github.com/ansible/creator-ee/pull/62
> Remove molecule-docker plugin from creator-ee

- Containerfile
- _build/requirements.yml
- execution-environment.yml
- tox.ini
That change finishes #65 and removes any docker use from our container. The root cause of this change being the conflicts caused by unmaintained community.docker collection which has a hard dependency on python docker-compose module, which is EOL (being replace by go implementation).
If the maintenance situation does change in the future, we might bring it back in but we cannot block other changes due to conflicts caused by it.
References:
* https://github.com/docker/compose/blob/master/setup.py#L28-L37 
* https://github.com/ansible-collections/community.docker/pull/360
* https://pypi.org/project/docker-compose/
> Remove community.docker and docker from creator-ee

- _build/requirements.txt
Fixes #140 
The current version is 2.10.4 which throws an error with cryptography > 37
> Specify paramiko 2.11.0

- tox.ini
Temporary disable most steps inside container, while we rework our
build pipelines to work with multi-arch containers as each run takes
more than 1.5h.
> Temporary empty container

- Containerfile
Add a label indicating this is an EE.
This will mimic future builder behaviour.
Also allows navigator to recognize this as an execution environment: https://github.com/ansible/ansible-navigator/pull/1317
> Add an EE label

- .pre-commit-config.yaml
- _build/requirements.txt
This should prevent pip from trying to install binary wheels.
> Added non-pure python packages to unsafe list

- Containerfile
- _build/shells
This fixes podman default user, which is using the /etc/shells.
> Ensure default shell is bash

- .github/workflows/task.yml
- .gitignore
- Containerfile
- Taskfile.yml
- _build/test-setup.sh
This should greatly increase the multi-arch container building speed by just installing collections from the host and avoiding running the installation from within the containers.
> Install collections from local

- _build/entrypoint.sh
> Fix readonly UID warning

- base/Containerfile
With the switch to fedora-minimal, python3 is no longer included in the base image for the creator-base.
Rather than pull it in as a dep for one of the python microdnf packages, explicitly install it.
The outcome is the same, but the installation of python3 is now explicit.
This will make it easier for future developers to test or modify the version of python being installed because it is listed as a first-class package.
> Specifically install python

- base/Containerfile
As we do not need the full git, it is better to only preinstall
git-core on base image.
> Install git-core instead of git on base image

- .github/workflows/release.yml
- .github/workflows/task.yml
- Taskfile.yml
- _build/validate
> Validate rpm and runner

- Containerfile
- Taskfile.yml
- _build/.bashrc
This adds a custom bash prompt for the container that consists of two lines
- (1st line) user, container tag name as hostname, current directory
- if the previous command failed a red exit code number is appended to 1st line
- 2nd line contains just the prompt, making easy to follow on screen by making less likely that that command would wrap on multiple lines.
> Add colored bash prompt

- Containerfile
* This was needed to get 'bash' inside the container to work correctly on a Fedora 37 with the new changes to add colors to the prompt
Resolves #293
> Add 'ncurses' Package To Provide 'tput'

- _build/requirements.txt
Add ansible-pylibssh to the python package requirements
(this is default for all network ssh connections)
> Add ansible-pylibssh

- _build/requirements.txt
- _build/test-setup.sh
Related: https://github.com/yaml/pyyaml/issues/601
When released, this should also fix the setup phase of testing in extension, which happens use py312 with requirements from this repository.
> Preinstall cython to avoid pyyaml installation errors
